name: juddsports
favicon: null
layout_spectrum: 0.38777
typography_spectrum: 0.85299
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#4c5154'
    - '#64252d'
    - '#85877e'
    - '#bfab97'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
